src/agendamento/urls.py
from django.urls import path
from . import views

app_name = "agendamento"

urlpatterns = [
    path("", views.pag_agenda, name="index"),
    path("api/", views.api_docs),
    path("api/raiz/", views.agendamento_lista),
    path("api/moderno/", views.AgendamentosListOrAdd.as_view()),
    path(
        "api/moderno/<int:agendamento_id>/",
        views.AgendamentoInfo.as_view(),
        name="detail",
    ),
    path("api/faturamento_mensal/", views.faturamento_mensal),
    path("disponiveis/", views.pag_disponibilidade, name="pagina_disponibilidade"),
    path("<int:agendamento_id>/", views.pag_unica, name="pagina_unica"),
]

src/nail_designer/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path("", views.homepage),
    path("sobre/", views.pag_sobre, name="sobre"),
    path("admin/", admin.site.urls),
    path("agendamento/", include("agendamento.urls")),
]

src/templates/homepage.html
{% extends "layout.html" %}
{% load static %}
{% block title %}
  Raissa Machado Naildesigner
{% endblock title %}
{% block extra_css %}
  <link rel="stylesheet" href="{% static 'styles/homepage.css' %}" />
{% endblock extra_css %}
{% block content %}
  <div class="homepage_catalogo">
      <div class="homepage_card">
        <div class="homepage_card_title">
          <p>Olá bem vindo a página da Api de Agendamento</p>
        </div>
      </div>
  </div>
{% endblock content %}

src/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}{% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'styles/layout.css' %}" />
    {% block extra_css %}{% endblock %}
  </head>
  <body>
    <header class="header_container">
      <div class="header">
        <a href="/" class="header_title">Nail Designer</a>
        <nav class="header_links">
          <a href="{% url 'sobre' %}">Sobre</a>,
          <a href="{% url 'agendamento:index' %}">Agendamentos</a>
        </nav>
      </div>
    </header>
    <main>
      {% block content %}{% endblock %}
    </main>
  </body>
</html>

src/templates/sobre.html
{% extends 'layout.html' %}
{% load static %}
{% block title %}
Sobre
{% endblock title %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'styles/about.css'%}">
{% endblock extra_css %}
{% block content %}
<p>Este é um aplicativo para agendamentos focado principalmente em quem trabalha com unhas. Criado por <a href="http://github.com/leandrogalbarino">
  Leandro Galbarino
</a>
</p>
{% endblock content %}