src/agendamento/urls.py
from django.urls import path
from . import views

app_name = "agendamento"

urlpatterns = [
    path("", views.pag_agenda, name="index"),
    path("api/", views.api_docs),
    path("api/raiz/", views.agendamento_lista),
    path("api/moderno/", views.AgendamentosListOrAdd.as_view()),
    path(
        "api/moderno/<int:agendamento_id>/",
        views.AgendamentoInfo.as_view(),
        name="detail",
    ),
    path("api/faturamento_mensal/", views.faturamento_mensal),
    path("disponiveis/", views.pag_disponibilidade, name="pagina_disponibilidade"),
    path("<int:agendamento_id>/", views.pag_unica, name="pagina_unica"),
]

src/nail_designer/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path("", views.homepage),
    path("sobre/", views.pag_sobre, name="sobre"),
    path("admin/", admin.site.urls),
    path("agendamento/", include("agendamento.urls")),
]

src/agendamento/models.py
from django.db import models
from datetime import datetime, date, time, timedelta
from django.core.exceptions import ValidationError
from django.db.models import Sum, Avg, Count, Value, DecimalField
from django.db.models.functions import Coalesce, Round


# Create your models here.
class Cliente(models.Model):
    cpf = models.CharField(max_length=11, unique=True)
    nome = models.CharField(max_length=50)
    sobrenome = models.CharField(max_length=50)
    email = models.EmailField()
    telefone = models.CharField(max_length=14)
    endereco = models.ForeignKey(
        "Endereco", on_delete=models.SET_NULL, null=True, blank=True
    )
    data_cadastro = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return f"{self.nome} {self.sobrenome}"


class Endereco(models.Model):
    cep = models.CharField(max_length=8)
    cidade = models.CharField(max_length=30)
    bairro = models.CharField(max_length=30)
    rua = models.CharField(max_length=30)
    numero = models.IntegerField()
    apartamento = models.CharField(max_length=10, null=True, blank=True)

    def __str__(self):
        eh_apartamento = self.apartamento if self.apartamento else ""
        if eh_apartamento:
            return f"Cep: {self.cep} | Num: {self.numero} | Apt: {self.apartamento} "
        return f"Cep: {self.cep} | Num: {self.numero} "


class AgendamentoManager(models.Manager):
    def obter_metricas_mensal(self, mes_inicio, mes_fim):
        metricas = self.filter(data__range=(mes_inicio, mes_fim)).aggregate(
            total_recebido=Round(
                Coalesce(Sum("valor_pago"), Value(0.00), output_field=DecimalField()), 2
            ),
            media_por_servico=Round(
                Coalesce(Avg("valor_pago"), Value(0.00), output_field=DecimalField()), 2
            ),
            total_atendimentos=Count("id"),
        )
        metricas["periodo"] = f"{mes_inicio} até {mes_fim}"
        return metricas


class Agendamento(models.Model):
    relatorios = AgendamentoManager()
    objects = models.Manager()

    data = models.DateField()
    horario_inicio = models.TimeField()
    horario_fim = models.TimeField()
    cliente = models.ForeignKey(
        "Cliente", on_delete=models.SET_NULL, null=True, blank=True
    )
    procedimento = models.ForeignKey(
        "Procedimento", on_delete=models.SET_NULL, null=True, blank=True
    )
    valor_pago = models.DecimalField(
        max_digits=6, decimal_places=2, null=True, blank=True, default=0.00
    )
    bloqueado = models.BooleanField(default=False)
    descricao = models.CharField(max_length=100, blank=True)

    class Meta:
        ordering = ["data"]

    def _verificar_conflitos_horarios(self):
        data = self.data
        margem = timedelta(minutes=15)

        novo_agendamento_inicio = datetime.combine(data, self.horario_inicio)
        novo_agendamento_fim = datetime.combine(data, self.horario_fim)
        conflitos = Agendamento.objects.filter(data=self.data).exclude(pk=self.pk)

        for item in conflitos:
            inicio_com_descanso = datetime.combine(data, item.horario_inicio) - margem
            fim_com_descanso = datetime.combine(data, item.horario_fim) + margem

            if (
                novo_agendamento_inicio < fim_com_descanso
                and novo_agendamento_fim > inicio_com_descanso
            ):
                raise ValidationError(
                    "Houve conflito de horários, por favor, verifique os horários disponiveis."
                )

    def _validar_intervalo_horario(self):
        self_inicio = datetime.combine(self.data, self.horario_inicio)
        self_fim = datetime.combine(self.data, self.horario_fim)
        if self_inicio >= self_fim:
            raise ValidationError(
                "O horário de fim precisa ser posteriormente ao de início."
            )

    def _inicializar_valor_pago(self):
        if self.valor_pago is None:
            if not self.bloqueado and self.procedimento:
                self.valor_pago = self.procedimento.valor
            else:
                self.valor_pago = 0.0

    def clean(self):
        super().clean()
        self._validar_intervalo_horario()
        self._verificar_conflitos_horarios()

    def save(self, *args, **kwargs):
        if not self.pk:
            self._inicializar_valor_pago()
        super().save(*args, **kwargs)

    def __str__(self):
        if self.bloqueado:
            informacao_bloqueo = (
                self.descricao if self.descricao else "Sem Informações."
            )
            return f"{self.data} | {self.horario_inicio}-{self.horario_fim}: Sem agendamento - {informacao_bloqueo}"
        nome_cliente = self.cliente.nome if self.cliente else "Anônimo"
        nome_procedimento = (
            self.procedimento.nome if self.procedimento else "Não definido"
        )
        return f"{self.data} | {self.horario_inicio} - {self.horario_fim}: {nome_cliente} - {nome_procedimento}"


class Procedimento(models.Model):
    nome = models.CharField(max_length=50)
    valor = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return self.nome

src/agendamento/views.py
from django.http import JsonResponse, HttpResponse
from rest_framework.parsers import JSONParser
from django.shortcuts import render, get_object_or_404

from datetime import datetime


from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from .models import Cliente, Agendamento
from .serializers import AgendamentoSerializer
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.decorators import api_view
from django.shortcuts import get_object_or_404

# Utilitarios do arquivo utils
from .utils import converter_data, intervalo_mes, data_ja_ocorreu


@csrf_exempt
def agendamento_lista(request):
    if request.method == "GET":
        data = datetime.now()
        agendamentos = Agendamento.objects.filter(data=data)
        serializer = AgendamentoSerializer(agendamentos, many=True)
        return JsonResponse(serializer.data, safe=False)
    elif request.method == "POST":
        dados = JSONParser().parse(request)
        serializer = AgendamentoSerializer(dados)
        if serializer.is_valid():
            return JsonResponse(serializer.data, status=201)
    return HttpResponse(status=405)


class AgendamentosListOrAdd(APIView):
    """
    Ver todos agendamento para o Dia ou Criar um novo agendamento
    """

    def get(self, request):
        filtros = request.query_params

        if "todos" in filtros and filtros["todos"]:
            agendamentos = Agendamento.objects.all()
        elif "data" in filtros:
            data = converter_data(filtros["data"])
            agendamentos = Agendamento.objects.filter(data=data)
        else:
            agendamentos = Agendamento.objects.filter(data=datetime.today().date())

        serializer = AgendamentoSerializer(agendamentos, many=True)
        return Response(serializer.data)

    def post(self, request):
        serializer = AgendamentoSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(
            serializer.errors,
            status=status.HTTP_400_BAD_REQUEST,
        )


class AgendamentoInfo(APIView):

    def get(self, request, agendamento_id):
        agendamento = get_object_or_404(Agendamento, pk=agendamento_id)
        serializer = AgendamentoSerializer(agendamento)
        return Response(serializer.data)

    def patch(self, request, agendamento_id):
        agendamento = get_object_or_404(Agendamento, pk=agendamento_id)
        serializer = AgendamentoSerializer(agendamento, data=request.data, partial=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, agendamento_id):
        agendamento = get_object_or_404(Agendamento, pk=agendamento_id)
        nome_cliente = agendamento.cliente.nome if agendamento.cliente else None
        agendamento.delete()

        if nome_cliente:
            mensagem = f"O agendamento com id: {agendamento_id} do cliente {nome_cliente} foi removido com sucesso."
        else:
            mensagem = (
                f"O agendamento com id: {agendamento_id} foi removido com sucesso."
            )

        return Response(
            {"mensagem": mensagem},
            status=status.HTTP_204_NO_CONTENT,
        )


@api_view(["GET"])
def api_docs(request):
    endpoints = {
        "raiz": "/agendamento/api/raiz",
        "moderno": "/agendamento/api/moderno",
        "faturamento": "/agendamento/api/faturamento_mensal",
        "dia": "/agendamento/api/agendamentos_dia",
    }
    return Response({"documentacao": endpoints}, status=status.HTTP_200_OK)


@api_view(["GET"])
def faturamento_mensal(request):

    filtros = request.query_params

    data_atual = datetime.today().date()
    mes_inicio, mes_fim = intervalo_mes(data_atual)

    if "data" in filtros:
        data_str = filtros.get("data")
        data = converter_data(data_str)
        if data_ja_ocorreu(data):
            mes_inicio, mes_fim = (
                intervalo_mes(data, todo_mes=True)
                if "mes_total" in filtros
                else intervalo_mes(data)
            )
        else:
            return Response(
                {
                    "erro": "Esta data ainda não ocorreu. por favor insira uma data válida para calculo do Faturamento."
                },
                status=status.HTTP_400_BAD_REQUEST,
            )

    metricas = Agendamento.relatorios.obter_metricas_mensal(
        mes_inicio=mes_inicio, mes_fim=mes_fim
    )

    return Response(metricas, status=status.HTTP_200_OK)


def index(request):
    lista_clientes = Cliente.objects.order_by("-data_cadastro")
    list = [
        {"id": 1},
        {"id": 2},
        {"id": 3},
        {"id": 4},
        {"id": 5},
    ]
    context = {"lista_clientes": lista_clientes, "lista": list}
    return render(request, "agendamento/index.html", context)


def cliente_pag(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk=cliente_id)
    return render(request, "agendamento/pagina_unica.html", {"cliente": cliente})


def results(request, cliente_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % cliente_id)


def vote(request, cliente_id):
    try:
        cliente = Cliente.objects.get(pk=cliente_id)
    except Cliente.DoesNotExist:
        return render(
            request,
            "agendamento/index.html",
            {
                "error_message": "You didn't select a choice.",
            },
        )
    message = f"O cliente {cliente.nome} votou na opção {request.POST["choice"]}"
    return HttpResponse(message)


def pag_agenda(request):
    agenda = Agendamento.objects.filter(data=datetime.now()).order_by("horario_inicio")
    return render(request, "agendamento/agenda.html", {"agenda": agenda})


def pag_disponibilidade(request):
    agenda = Agendamento.objects.filter(data=datetime.now()).order_by("horario_inicio")
    return render(request, "agendamento/agenda.html", {"agenda": agenda})


def pag_unica(request, agendamento_id):
    horario = get_object_or_404(Agendamento, pk=agendamento_id)
    return render(request, "agendamento/pagina_unica.html", {"reserva": horario})

src/agendamento/templates/agendamento/agenda.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Agendamento</title>
</head>
<body>
  <div>
    <p>Agendamentos para hoje:</p>
    {% for item in agenda %}
      <div>
        <div><a href="{% url 'agendamento:pagina_unica' item.id %}">{{ item }}</a></div>
      </div>  
        {% empty %}
        <p>Não há agendamentos para hoje!</p>
    {% endfor %}
  </div>
</body>
</html>

src/agendamento/templates/agendamento/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
    {% if lista_clientes %}
      <ul>
      {% for cliente in lista_clientes %}
          <li><a href="{% url "agendamento:cliente_pagina" cliente.id %}">{{ cliente.nome }}</a></li>
          <form action="{% url 'agendamento:vote' cliente.id %}" method="post">
            {% csrf_token %}
            <fieldset>
                <legend><h1>{{ cliente.nome }} </h1></legend>
                {% if error_message %} <p>{{ error_message }}</p> {% endif %}
                {% for choice in lista %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="20"/>
                {% endfor %}
            </fieldset>
            <input type="submit" value="vote">  
            </form>
          {% endfor %}
      </ul>
      {% else %}
          <p>No polls are available.</p>
    {% endif %}
</body>
</html>

src/agendamento/templates/agendamento/pagina_unica.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
    <div>
      <div>
        <span>{{ reserva.cliente }}</span>
      </div>
      <div>
        <span>{{ reserva.procedimento }}</span>
      </div>
      <div>
        <span>Inicio: {{ reserva.horario_inicio }}</span>
      </div>
      <div>
        <span>Fim: {{ reserva.horario_fim }}</span>
      </div>
      <div>
        <span>Valor cobrado: {{ reserva.valor_pago }}</span>
      </div>
    </div>
<body/>
</html>

src/agendamento/templates/agendamento/vote.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
    {% if cliente %}
      <div>
        <label>Nome:</label>
        <span>{{ cliente.nome }} {{ cliente.sobrenome }}</span>
      </div>
      <div>
        <label>Email:</label>
        <span>{{ cliente.email }}</span>
      </div>
      <div>
        <label>Telefone:</label>
        <span>{{ cliente.telefone }}</span>
      </div>
      <div>
        <label>Endereço:</label>
        <span>{{ cliente.endereco.cidade }}
          {{ cliente.endereco.bairro}} {{ cliente.endereco.rua}}
          {{ cliente.endereco.num}}
          {% if cliente.endereco.apartamento %}
            {{ cliente.endereco.apartamento }}
          {% endif %}
        </span>
      </div> 
    {% endif %}
</body>
</html>